const promptEngineeringQuestions = [
    {
      id: 1,
      title: "What is prompt engineering?",
      type: "Prompt Engineering",
      description: "Prompt engineering is the process of designing and refining prompts to effectively communicate with language models.",
      example: "Example: Crafting a prompt to elicit a specific type of response from an AI."
    },
    {
      id: 2,
      title: "What are the components of a prompt?",
      type: "Prompt Engineering",
      description: "The main components of a prompt include the instruction, context, and desired output format.",
      example: "Example: 'Translate the following text into French: [text]'"
    },
    {
      id: 3,
      title: "Why is specificity important in prompt engineering?",
      type: "Prompt Engineering",
      description: "Specificity helps guide the model's response, reducing ambiguity and increasing relevance.",
      example: "Example: Instead of asking 'Tell me about dogs,' ask 'What are the top three dog breeds for families?'"
    },
    {
      id: 4,
      title: "What is the role of context in prompts?",
      type: "Prompt Engineering",
      description: "Context provides background information that helps the model generate more accurate and relevant responses.",
      example: "Example: Providing a brief overview of a topic before asking a question about it."
    },
    {
      id: 5,
      title: "How can you test the effectiveness of a prompt?",
      type: "Prompt Engineering",
      description: "By comparing the responses generated by different prompts and analyzing their relevance and quality.",
      example: "Example: Running A/B tests with various prompt formulations to see which yields better results."
    },
    {
      id: 6,
      title: "What are examples of effective prompt formats?",
      type: "Prompt Engineering",
      description: "Effective prompt formats include questions, instructions, and fill-in-the-blank structures.",
      example: "Example: 'What are the benefits of exercise? List three advantages.'"
    },
    {
      id: 7,
      title: "What is a zero-shot prompt?",
      type: "Prompt Engineering",
      description: "A zero-shot prompt is when the model is asked to perform a task without prior examples or training specific to that task.",
      example: "Example: 'Summarize the following article in one sentence.'"
    },
    {
      id: 8,
      title: "What is a few-shot prompt?",
      type: "Prompt Engineering",
      description: "A few-shot prompt includes a few examples to guide the model in generating a response.",
      example: "Example: Providing a few sample questions and answers to illustrate the desired format."
    },
    {
      id: 9,
      title: "How can you improve the quality of AI responses?",
      type: "Prompt Engineering",
      description: "By refining prompts to be more specific, clear, and contextually rich.",
      example: "Example: Instead of 'Write a story,' try 'Write a 100-word story about a cat who explores a new neighborhood.'"
    },
    {
      id: 10,
      title: "What is an instruction-based prompt?",
      type: "Prompt Engineering",
      description: "An instruction-based prompt explicitly tells the model what task to perform.",
      example: "Example: 'Generate a list of healthy breakfast options.'"
    },
    {
      id: 11,
      title: "What are common pitfalls in prompt engineering?",
      type: "Prompt Engineering",
      description: "Common pitfalls include vagueness, complexity, and assumptions about the model's knowledge.",
      example: "Example: Asking 'Explain everything about climate change' can lead to overly broad responses."
    },
    {
      id: 12,
      title: "How does temperature affect model responses?",
      type: "Prompt Engineering",
      description: "Temperature controls the randomness of the model's outputs; higher temperatures result in more diverse responses.",
      example: "Example: A temperature setting of 0.7 might yield creative responses, while 0.2 will be more focused."
    },
    {
      id: 13,
      title: "What is prompt chaining?",
      type: "Prompt Engineering",
      description: "Prompt chaining involves using the output of one prompt as the input for another, creating a sequence of prompts.",
      example: "Example: Asking the model to generate an outline and then requesting a detailed section based on that outline."
    },
    {
      id: 14,
      title: "How can you mitigate biases in AI responses?",
      type: "Prompt Engineering",
      description: "By carefully designing prompts that are neutral and inclusive, and by evaluating outputs for biased content.",
      example: "Example: Avoiding prompts that imply stereotypes or assumptions about groups of people."
    },
    {
      id: 15,
      title: "What is a multi-turn prompt?",
      type: "Prompt Engineering",
      description: "A multi-turn prompt involves a conversation with the model, where the context builds over several interactions.",
      example: "Example: Asking follow-up questions based on the model's previous responses."
    },
    {
      id: 16,
      title: "What are some strategies for handling ambiguity in prompts?",
      type: "Prompt Engineering",
      description: "Strategies include clarifying the question, providing examples, or specifying the desired output format.",
      example: "Example: Instead of 'Describe a fruit,' ask 'Describe an apple, focusing on its taste and texture.'"
    },
    {
      id: 17,
      title: "How do different models affect prompt engineering?",
      type: "Prompt Engineering",
      description: "Different models may have varying strengths and weaknesses, influencing how prompts should be crafted.",
      example: "Example: A model trained on technical data may respond better to technical prompts compared to casual ones."
    },
    {
      id: 18,
      title: "What is prompt bias?",
      type: "Prompt Engineering",
      description: "Prompt bias occurs when a prompt leads the model to produce biased or unbalanced outputs.",
      example: "Example: A prompt that emphasizes one perspective over another can skew the response."
    },
    {
      id: 19,
      title: "How can you create engaging prompts?",
      type: "Prompt Engineering",
      description: "Engaging prompts often involve storytelling elements, intriguing questions, or relatable scenarios.",
      example: "Example: 'Imagine you are a detective; describe your latest case.'"
    },
    {
      id: 20,
      title: "What is the importance of iteration in prompt engineering?",
      type: "Prompt Engineering",
      description: "Iteration allows for continuous improvement of prompts based on feedback and observed model behavior.",
      example: "Example: Testing multiple versions of a prompt to identify which yields the best results."
    },
    {
      id: 21,
      title: "What are some tools for prompt engineering?",
      type: "Prompt Engineering",
      description: "Tools include prompt builders, evaluation frameworks, and user interfaces for testing prompts with models.",
      example: "Example: Using platforms that allow users to experiment with different prompt formulations."
    },
    {
      id: 22,
      title: "What role does feedback play in prompt engineering?",
      type: "Prompt Engineering",
      description: "Feedback helps identify weaknesses in prompts and informs adjustments to improve response quality.",
      example: "Example: User feedback indicating confusion can lead to prompt clarification."
    },
    {
      id: 23,
      title: "What is role-playing in prompt engineering?",
      type: "Prompt Engineering",
      description: "Role-playing involves framing the prompt as if the model is taking on a specific role or persona.",
      example: "Example: 'You are a travel guide; recommend three destinations for adventure seekers.'"
    },
    {
      id: 24,
      title: "What is the significance of prompt length?",
      type: "Prompt Engineering",
      description: "Prompt length can influence the model's understanding; concise prompts may lead to more focused responses.",
      example: "Example: A short prompt may yield quick answers, while a long, detailed prompt may result in richer responses."
    },
    {
      id: 25,
      title: "What is the effect of using examples in prompts?",
      type: "Prompt Engineering",
      description: "Using examples can clarify expectations and guide the model toward the desired output format.",
      example: "Example: 'Translate the following phrases: 'Hello' → 'Bonjour'; 'Goodbye' → 'Au revoir.'"
    },
    {
      id: 26,
      title: "How does the audience affect prompt design?",
      type: "Prompt Engineering",
      description: "Understanding the target audience can help tailor prompts to their knowledge level and interests.",
      example: "Example: Using technical jargon for experts vs. plain language for general audiences."
    },
    {
      id: 27,
      title: "What is prompt formatting?",
      type: "Prompt Engineering",
      description: "Prompt formatting involves the visual and structural design of prompts to enhance clarity and engagement.",
      example: "Example: Using bullet points or numbered lists to organize information within a prompt."
    },
    {
      id: 28,
      title: "What is the impact of ambiguity in prompts?",
      type: "Prompt Engineering",
      description: "Ambiguity can lead to unclear or irrelevant responses from the model, making precision essential.",
      example: "Example: A prompt like 'Discuss technology' may yield broad, unfocused responses."
    },
    {
      id: 29,
      title: "What are context windows in prompt engineering?",
      type: "Prompt Engineering",
      description: "Context windows refer to the amount of previous text the model can consider when generating responses.",
      example: "Example: Keeping prompts within the model's context window to maintain relevance in multi-turn interactions."
    },
    {
      id: 30,
      title: "How do you optimize for creative responses?",
      type: "Prompt Engineering",
      description: "To optimize for creativity, prompts can be designed to encourage imaginative thinking and open-ended exploration.",
      example: "Example: 'Invent a new holiday and describe how it is celebrated.'"
    },
    {
      id: 31,
      title: "What are some common metrics for evaluating prompt effectiveness?",
      type: "Prompt Engineering",
      description: "Metrics may include relevance, coherence, engagement, and user satisfaction.",
      example: "Example: Surveying users for their opinions on the helpfulness of responses generated by different prompts."
    },
    {
      id: 32,
      title: "What is the relationship between prompt length and output quality?",
      type: "Prompt Engineering",
      description: "Longer prompts can provide more context but may also overwhelm the model, affecting output quality.",
      example: "Example: Finding a balance between providing sufficient information without unnecessary complexity."
    },
    {
      id: 33,
      title: "How do different languages affect prompt engineering?",
      type: "Prompt Engineering",
      description: "Different languages may require unique phrasing and cultural considerations in prompt design.",
      example: "Example: Idiomatic expressions may not translate well across languages, necessitating careful phrasing."
    },
    {
      id: 34,
      title: "What are the implications of prompt phrasing?",
      type: "Prompt Engineering",
      description: "The way a prompt is phrased can significantly impact the model's interpretation and response.",
      example: "Example: Asking 'What are your thoughts?' vs. 'List three benefits of.' can yield different response types."
    },
    {
      id: 35,
      title: "How can prompts be tailored for different tasks?",
      type: "Prompt Engineering",
      description: "Prompts can be customized based on the nature of the task, such as summarization, translation, or conversation.",
      example: "Example: Tailoring prompts to provide direct instructions for specific tasks or open-ended questions for discussion."
    },
    {
        id: 36,
        title: "What is a prompt template?",
        type: "Prompt Engineering",
        description: "A prompt template is a pre-defined structure that can be filled in with specific data or variables to generate prompts efficiently.",
        example: "Example: 'As a [role], explain [topic] to a [audience].'"
      },
      {
        id: 37,
        title: "How does prompt specificity affect model responses?",
        type: "Prompt Engineering",
        description: "Specific prompts guide the model to generate targeted responses, reducing ambiguity and enhancing relevance.",
        example: "Example: 'List five healthy snack options for kids' vs. 'List snacks.'"
      },
      {
        id: 38,
        title: "What is an anchor in prompt engineering?",
        type: "Prompt Engineering",
        description: "An anchor is a specific term or phrase within a prompt that guides the model's response toward a particular topic or theme.",
        example: "Example: Using 'environmental impact' as an anchor in prompts about sustainability."
      },
      {
        id: 39,
        title: "How can prompts incorporate user context?",
        type: "Prompt Engineering",
        description: "By personalizing prompts based on user data or previous interactions, you can increase engagement and relevance.",
        example: "Example: 'Based on your previous interests in hiking, what are the best trails in your area?'"
      },
      {
        id: 40,
        title: "What is a directive prompt?",
        type: "Prompt Engineering",
        description: "A directive prompt gives clear instructions on what the model should do, guiding it to produce a desired output.",
        example: "Example: 'Create a summary of the following text in bullet points.'"
      },
      {
        id: 41,
        title: "How can negative prompts be used?",
        type: "Prompt Engineering",
        description: "Negative prompts specify what should not be included in the response, helping to clarify expectations.",
        example: "Example: 'Describe a fruit but do not mention apples or oranges.'"
      },
      {
        id: 42,
        title: "What is the significance of output diversity?",
        type: "Prompt Engineering",
        description: "Encouraging output diversity allows for a wider range of responses, which can lead to more creative and engaging interactions.",
        example: "Example: Using a higher temperature setting can lead to more varied outputs."
      },
      {
        id: 43,
        title: "What is a context-rich prompt?",
        type: "Prompt Engineering",
        description: "A context-rich prompt provides background information to help the model generate more informed and accurate responses.",
        example: "Example: 'Given the recent climate reports, summarize the key findings.'"
      },
      {
        id: 44,
        title: "How can prompts be used for learning?",
        type: "Prompt Engineering",
        description: "Prompts can facilitate learning by guiding users through explanations, examples, and practice questions.",
        example: "Example: 'Explain the concept of photosynthesis and provide an example of a plant that uses it.'"
      },
      {
        id: 45,
        title: "What is a follow-up prompt?",
        type: "Prompt Engineering",
        description: "A follow-up prompt builds on a previous response, encouraging further elaboration or exploration of a topic.",
        example: "Example: 'Can you provide more details on that?'"
      },
      {
        id: 46,
        title: "How do prompts affect user engagement?",
        type: "Prompt Engineering",
        description: "Well-crafted prompts can increase user engagement by making interactions more interesting and relevant.",
        example: "Example: Engaging prompts that invite users to share opinions or experiences can foster interaction."
      },
      {
        id: 47,
        title: "What is a context switch in prompt engineering?",
        type: "Prompt Engineering",
        description: "A context switch occurs when the model transitions between different topics or themes in a conversation, requiring careful prompt design.",
        example: "Example: Switching from discussing technology to discussing health requires clear prompts to maintain coherence."
      },
      {
        id: 48,
        title: "How can humor be incorporated into prompts?",
        type: "Prompt Engineering",
        description: "Incorporating humor can make prompts more engaging and relatable, encouraging users to respond positively.",
        example: "Example: 'If you were a vegetable, what kind would you be and why?'"
      },
      {
        id: 49,
        title: "What is a scenario-based prompt?",
        type: "Prompt Engineering",
        description: "Scenario-based prompts present hypothetical situations for the model to explore, encouraging creative thinking.",
        example: "Example: 'Imagine you are an astronaut; describe your first day on Mars.'"
      },
      {
        id: 50,
        title: "What is a feedback loop in prompt engineering?",
        type: "Prompt Engineering",
        description: "A feedback loop allows for continuous refinement of prompts based on user responses and model performance.",
        example: "Example: Collecting user feedback on responses to improve prompt quality over time."
      },
      {
        id: 51,
        title: "How can prompts be tailored for different age groups?",
        type: "Prompt Engineering",
        description: "Tailoring prompts based on the target age group ensures that language, complexity, and content are appropriate.",
        example: "Example: Using simpler language for younger audiences versus technical terms for adults."
      },
      {
        id: 52,
        title: "What is the impact of cultural context in prompt engineering?",
        type: "Prompt Engineering",
        description: "Cultural context can influence how prompts are interpreted and should be considered when crafting them.",
        example: "Example: Phrasing questions in a way that respects cultural norms and sensitivities."
      },
      {
        id: 53,
        title: "What role does prompt tone play?",
        type: "Prompt Engineering",
        description: "The tone of a prompt (e.g., formal, casual, humorous) can affect how users perceive the interaction.",
        example: "Example: A friendly tone can make users feel more comfortable engaging with the model."
      },
      {
        id: 54,
        title: "What is a multi-modal prompt?",
        type: "Prompt Engineering",
        description: "Multi-modal prompts incorporate various types of input (text, images, audio) to enhance the interaction.",
        example: "Example: Asking users to describe an image and then generate a story based on that description."
      },
      {
        id: 55,
        title: "How can prompts foster critical thinking?",
        type: "Prompt Engineering",
        description: "Prompts that encourage analysis, evaluation, and synthesis of information can enhance critical thinking skills.",
        example: "Example: 'Evaluate the pros and cons of remote work versus in-office work.'"
      },
      {
        id: 56,
        title: "What is a prompt genre?",
        type: "Prompt Engineering",
        description: "Different genres of prompts (e.g., narrative, expository, persuasive) can shape the type of response generated.",
        example: "Example: A narrative prompt like 'Tell me a story about a brave knight' invites creative storytelling."
      },
      {
        id: 57,
        title: "How does prompt framing affect responses?",
        type: "Prompt Engineering",
        description: "The way a prompt is framed can significantly influence the perspective from which the model approaches a topic.",
        example: "Example: Asking 'What are the risks of climate change?' vs. 'What are the benefits of addressing climate change?'"
      },
      {
        id: 58,
        title: "What is a character-driven prompt?",
        type: "Prompt Engineering",
        description: "A character-driven prompt involves framing the prompt from the perspective of a specific character or persona.",
        example: "Example: 'As a historian, describe the life of a famous figure during the Renaissance.'"
      },
      {
        id: 59,
        title: "How can you create prompts for collaborative projects?",
        type: "Prompt Engineering",
        description: "Designing prompts that encourage collaboration can enhance group dynamics and idea sharing.",
        example: "Example: 'In teams, brainstorm three innovative solutions to reduce plastic waste.'"
      },
      {
        id: 60,
        title: "What is the role of empathy in prompt engineering?",
        type: "Prompt Engineering",
        description: "Empathy can help design prompts that resonate with users, fostering deeper connections and engagement.",
        example: "Example: 'How would you feel if you lost your job during a pandemic? Share your thoughts.'"
      }
  ];
   export default promptEngineeringQuestions